Test

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -11,12 +11,19 @@ steps:
         echo "Calling Looker APIs."
   
         looker_token=$(curl --request POST 'https://${_LOOKER_INSTANCE}/api/4.0/login?client_id='$$LOOKER_API_CLIENT_ID'&client_secretxx='$$LOOKER_API_CLIENT_SECRET | sed -e 's/{"access_token":"\(.*\)","token_type.*/\1/')
-        echo $looker_token
         if [[ $looker_token == *"<html>"* ]]; then
-          echo "Error has occured"
+          echo "Error has occured while obtaining the token."
+          echo $looker_token
           exit 125
         fi
-        curl --request POST 'https://${_LOOKER_INSTANCE}/api/4.0/projects/${_LOOKER_PROJECT}/deploy_ref_to_production?branch' --header "Authorization: Bearer $looker_token"
+        
+        looker_response=$(curl --request POST 'https://${_LOOKER_INSTANCE}/api/4.0/projects/${_LOOKER_PROJECT}/deploy_ref_to_production?branch' --header "Authorization: Bearer $looker_token")
+        if [[ $looker_response == *"Requires authentication"* ] || [ $looker_response == *"<HTML>"* ]]; then
+          echo "Error has occured while running Looker POST API"
+          echo $looker_response
+          exit 125
+        fi
+        
         echo "Looker APIs calls are successfully finished."  
 
     entrypoint: bash
