Test

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -12,7 +12,10 @@ steps:
   
         looker_token=$(curl --request POST 'https://${_LOOKER_INSTANCE}/api/4.0/login?client_id='$$LOOKER_API_CLIENT_ID'&client_secret='$$LOOKER_API_CLIENT_SECRET | sed -e 's/{"access_token":"\(.*\)","token_type.*/\1/')
         echo $looker_token
-        
+        if [[ $looker_token == *"<html>"* ]]; then
+          echo "Error has occured"
+          exit 125
+        fi
         curl --request POST 'https://${_LOOKER_INSTANCE}/api/4.0/projects/${_LOOKER_PROJECT}/deploy_ref_to_production?branch' --header "Authorization: Bearer $looker_token"
         echo "Looker APIs calls are successfully finished."  
 
